let romsData = {
    最爱: [
        ['快打旋风', 'roms/1981/kuaidaxuanfeng.nes'],
        ['炸弹人1 (J) Bomberman [!]', 'roms/rom1/(J) Bomberman [!].nes'],
        ['忍者', 'roms/1981//ninja.nes'],
        ['激龟快打', 'roms/1981/HeroTurtles.nes'],
        ['炸弹人2', 'roms/1981/boomman.nes'],
        ['雪人兄弟', 'roms/1981/Snow Bros. (J).nes'],
        ['冒险岛4', 'roms/1981/maoxiandao.nes'],
        ['加纳战机', 'roms/1981/Gun-Nac.nes'],
        ['三目童子', 'roms/1981/sanmotz.nes'],
        ['魂斗罗1(U)30S', 'roms/Contra/Contra1(U)30S.nes'],
        ['超级马里奥1 (W) Super Mario Bros. [!]', 'roms/rom1/(W) Super Mario Bros. [!].nes'],
        ['双截龙2 Double Dragon2', 'roms/Double Dragon/Double Dragon2.nes'],
    ],
    魂斗罗: [
        ['魂斗罗1(U)30', 'roms/Contra/Contra1(U)30.nes'],
        ['魂斗罗1(U)30F', 'roms/Contra/Contra1(U)30F.nes'],
        ['魂斗罗1(U)30L', 'roms/Contra/Contra1(U)30L.nes'],
        ['魂斗罗1(U)30M', 'roms/Contra/Contra1(U)30M.nes'],
        ['魂斗罗1(U)F', 'roms/Contra/Contra1(U)F.nes'],
        ['魂斗罗1(U)L', 'roms/Contra/Contra1(U)L.nes'],
        ['魂斗罗1(U)M', 'roms/Contra/Contra1(U)M.nes'],
        ['魂斗罗1(U)S', 'roms/Contra/Contra1(U)S.nes'],
    ],
    超级玛丽: [
        [
            '超级马里奥3 (W) Super Mario Bros. 3 (U)',
            'roms/bfirsh/Super Mario Bros. 3 (U) (PRG1) [!].nes',
        ],
        ['马里奥拆屋工 (W) Wrecking Crew [!]', 'roms/rom1/(W) Wrecking Crew [!].nes'],
        ['马里奥医生 Dr. Mario (JU)', 'roms/bfirsh/Dr. Mario (JU).nes'],
    ],
    双截龙: [
        ['双截龙1 Double Dragon1', 'roms/Double Dragon/Double Dragon1.nes'],
        ['双截龙3 Double Dragon3', 'roms/Double Dragon/Double Dragon3.nes'],
        ['双截龙4 Double Dragon4', 'roms/Double Dragon/Double Dragon4.nes'],
    ],
    俄罗斯方块: [
        ['俄罗斯方块LJ65', 'roms/lj65/lj65.nes'],
        ['俄罗斯方块Tetris(U)', 'roms/other/Tetris (U) [!].nes'],
        ['俄罗斯方块Tetris 2(U)', 'roms/other/Tetris 2 (U) [!].nes'],
    ],
    坦克: [
        ['坦克 (Ch) Missile Tank', 'roms/rom1/(Ch) Missile Tank.nes'],
        ['坦克 (Ch) Tank 1990', 'roms/rom1/(Ch) Tank 1990.nes'],
        ['坦克 (J) Battle City', 'roms/rom1/(J) Battle City.nes'],
    ],
    经典: [
        ['赤影战士 Kage', 'roms/other/Kage.nes'],
        ['中国象棋', 'roms/other/Zhong Guo Xiang Qi.nes'],
        ['吃豆精灵 (J) (V1.1) Pac-Man [!]', 'roms/other/Pac-Man.nes'],
        ['摩托车大赛 (J) (PRG1) Mach Rider [!]', 'roms/other/Mach Rider.nes'],
        ['沙罗曼蛇 (U) Life Force', 'roms/rom2/Life Force [!].nes'],
        ['1943 (U) 1943 - The Battle of Midway', 'roms/rom2/1943.nes'],
        ['脱狱 Cross Fire (J)', 'roms/rom2/Cross Fire (J).nes'],
        ['撞球咖啡馆 Shufflepuck Cafe', 'roms/rom2/Shufflepuck Cafe.nes'],
        ['功夫 (J) (V1.2) Yie Ar Kung-Fu [!]', 'roms/rom1/(J) (V1.2) Yie Ar Kung-Fu [!].nes'],
    ],
    淘金者: [
        ['淘金者(汉化)', 'roms/rom1/TaoJinZhe.nes'],
        ['淘金者(J)', 'roms/rom1/Championship Lode Runner (J).nes'],
    ],

    赛车: [
        ['F1赛车 (J) F-1 Race [!]', 'roms/rom1/(J) F-1 Race [!].nes'],
        ['摩托车大赛 (JU) (PRG0) Mach Rider [!]', 'roms/rom1/(JU) (PRG0) Mach Rider [!].nes'],
        ['越野机车 (JU) Excitebike [!]', 'roms/rom1/(JU) Excitebike [!].nes'],
        ['火箭车 (J) Road Fighter [!]', 'roms/rom1/(J) Road Fighter [!].nes'],
    ],

    其它: [
        ['泡泡 Bubble Bobble (U)', 'roms/bfirsh/Bubble Bobble (U).nes'],
        ['Concentration Room', 'roms/croom/croom.nes'],
        ['网球Tennis(JU)', 'roms/other/Tennis (JU) [!].nes'],
        ['高尔夫 Golf (JU)', 'roms/bfirsh/Golf (JU).nes'],
        [
            'Zelda II - The Adventure of Link(U)',
            'roms/other/Zelda II - The Adventure of Link (U).nes',
        ],
        ['地底探险1 (J) Spelunker [!]', 'roms/rom1/(J) Spelunker [!].nes'],
        ['快乐猫 (J) Mappy [!]', 'roms/rom1/(J) Mappy [!].nes'],
        ['成龙踢馆1 (J) Spartan X [!]', 'roms/rom1/(J) Spartan X [!].nes'],
        ['敲冰块 (J) Ice Climber', 'roms/rom1/(J) Ice Climber.nes'],
        ['猪小弟 (J) Pooyan', 'roms/rom1/(J) Pooyan.nes'],
        ['马戏团 (J) Circus Charlie [!]', 'roms/rom1/(J) Circus Charlie [!].nes'],
    ],
};

romsData.keyMap = {
    8: 'Backspace',
    9: 'Tab',
    13: 'Enter',
    16: 'ShiftLeft',
    17: 'ControlLeft',
    18: 'AltLeft',
    19: 'Pause',
    20: 'CapsLock',
    27: 'Escape',
    32: 'Space',
    33: 'PageUp',
    34: 'PageDown',
    35: 'End',
    36: 'Home',
    37: 'ArrowLeft',
    38: 'ArrowUp',
    39: 'ArrowRight',
    40: 'ArrowDown',
    45: 'Insert',
    46: 'Delete',
    48: 'Digit0',
    49: 'Digit1',
    50: 'Digit2',
    51: 'Digit3',
    52: 'Digit4',
    53: 'Digit5',
    54: 'Digit6',
    55: 'Digit7',
    56: 'Digit8',
    57: 'Digit9',
    65: 'KeyA',
    66: 'KeyB',
    67: 'KeyC',
    68: 'KeyD',
    69: 'KeyE',
    70: 'KeyF',
    71: 'KeyG',
    72: 'KeyH',
    73: 'KeyI',
    74: 'KeyJ',
    75: 'KeyK',
    76: 'KeyL',
    77: 'KeyM',
    78: 'KeyN',
    79: 'KeyO',
    80: 'KeyP',
    81: 'KeyQ',
    82: 'KeyR',
    83: 'KeyS',
    84: 'KeyT',
    85: 'KeyU',
    86: 'KeyV',
    87: 'KeyW',
    88: 'KeyX',
    89: 'KeyY',
    90: 'KeyZ',
    91: 'MetaLeft',
    93: 'ContextMenu',
    96: 'Numpad0',
    97: 'Numpad1',
    98: 'Numpad2',
    99: 'Numpad3',
    100: 'Numpad4',
    101: 'Numpad5',
    102: 'Numpad6',
    103: 'Numpad7',
    104: 'Numpad8',
    105: 'Numpad9',
    106: 'NumpadMultiply',
    107: 'NumpadAdd',
    109: 'NumpadSubtract',
    110: 'NumpadDecimal',
    111: 'NumpadDivide',
    112: 'F1',
    113: 'F2',
    114: 'F3',
    115: 'F4',
    116: 'F5',
    117: 'F6',
    118: 'F7',
    120: 'F9',
    121: 'F10',
    122: 'F11',
    123: 'F12',
    144: 'NumLock',
    145: 'ScrollLock',
    186: 'Semicolon',
    187: 'Equal',
    188: 'Comma',
    189: 'Minus',
    190: 'Period',
    191: 'Slash',
    192: 'Backquote',
    219: 'BracketLeft',
    220: 'Backslash',
    221: 'BracketRight',
    222: 'Quote',
};
export { romsData };
